# Generated by Django 6.0 on 2025-12-11 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('costing_method', models.CharField(choices=[('FIFO', 'First-In First-Out'), ('LIFO', 'Last-In First-Out'), ('AVG', 'Weighted Average')], default='FIFO', max_length=4)),
                ('description', models.TextField(blank=True)),
                ('length', models.FloatField(default=0, help_text='cm')),
                ('width', models.FloatField(default=0, help_text='cm')),
                ('height', models.FloatField(default=0, help_text='cm')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_qty', models.IntegerField()),
                ('current_qty', models.IntegerField()),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='PO Number or Transfer ID', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Stock Batches',
                'ordering': ['received_date'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase In'), ('SALE', 'Sale Out'), ('RETURN', 'Customer Return'), ('ADJUST', 'Inventory Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Negative for outflow, Positive for inflow')),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.stockbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product', 'warehouse', 'current_qty'], name='inventory_s_product_ecba95_idx'),
        ),
    ]
